name: 05 Matrix

on: [workflow_dispatch]

jobs:
  matrix-demo:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ["1", "2", "3"]
    steps:
      - run: echo "Running matrix item version=${{ matrix.version }}"
